// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amklbbxnfhudzcgnvlfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFta2xiYnhuZmh1ZHpjZ252bGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTM4NzcsImV4cCI6MjA2NDk2OTg3N30.N0s_7COMRI-H48O9IkkPdWl4pzu6VJeOkSoN5Er7vGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);